### ISSUE TITLE
License

### ISSUE THREAD

**Issue by xfreib00** [jansvoboda11/gram#3]
Hi, 
I want to base my project on your library, but I noticed you have not specified any kind of license for your project, and since your project is library this acitvely forbids any derivative projects based on your library. 

I would suggest adding some kind of license (like MIT or Apache) to make your project more accessible.

According to [Github's documentation](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#choosing-the-right-license)

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license.

**Comment by jansvoboda11** [comment]
Thanks, I didn't realize the license was missing. Solved in #4.
